###
POST http://localhost:8001/api/members
Content-Type: application/json

{
  "documento": 33999999,
  "tipo": "DU",
  "tomo": 33,
  "folio": 555,
  "apellidoNombre": "Popis",
  "direccion": "algun ligar 444",
  "calificativo": "SIN",
  "telefono": "24589346734",
  "lugar": "por ahi",
  "correo": "algo@gmail.com"
}

###
GET http://localhost:8001/api/members

###
GET http://localhost:8001/api/members/6338c16dfcf6a12031d10a1a

###
PATCH http://localhost:8001/api/members/6338c16dfcf6a12031d10a1a
Content-Type: application/json

{
  "name": "Pipo"
}